[metadata]
name = dbt-conveyor-snowflake
description = The ConveyorSnowflake adapter plugin for dbt
author = Stijn De Haes
author_email = stijn.dehaes@dataminded.be
url = https://github.com/datamindedbe/dbt-conveyor-snowflake
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Development Status :: 3 - Alpha
    Operating System :: OS Independent
    Programming Language :: Python

[options]
packages = find_namespace:
include_package_data = True
install_requires =
    dbt-core~=1.11.12
    dbt-snowflake~=1.11.6

[options.packages.find]
include =
    dbt
    dbt.*
